application/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('index');
});

Route::group(['prefix' => 'admin'], function() {
    Route::get('/', 'Admin\NewsController@index')->name('admin.index');

    Route::resource('news', 'Admin\NewsController')->names([
        'create' => 'admin.create',
        'edit' => 'admin.edit',
        'destroy' => 'admin.destroy'
    ]);
});

Route::get('/news', ['uses' => 'NewsController@index'])->name('news.all');
Route::get('/news/{slug}', ['uses' => 'NewsController@show'])->name('news.one');

application/app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;

/**
 * Class News
 * @package App
 *
 * @method static $this where($column, $operator = null, $value = null, $boolean = 'and')
 * @method Model|Builder firstOrFail($columns = ['*'])
 * @method static LengthAwarePaginator paginate($perPage = null, $columns = ['*'], $pageName = 'page', $page = null)
 */
class News extends Model
{
    /**
     * @var array
     */
    protected $fillable = [
        'title',
        'slug',
        'timestamp_publish',
        'description',
        'content'
    ];

    /**
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }
}

application/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

application/app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\News;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $news = News::paginate(env('PAGINATE_COUNT_NEWS_ADMIN', 2));
        return view('admin.news.index', compact('news'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.news.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => [
                'required',
                'min:3',
                'max:128',
                'unique:news,title,' . $request->get('title')
            ],
            'description' => 'required',
            'content' => 'required',
            'timestamp_publish' => 'required'
        ], [
            'timestamp_publish.required' => 'The date publish field is required.'
        ]);

        $news = new News([
            'title' => $request->get('title'),
            'slug' => Str::slug($request->get('title')),
            'description' => $request->get('description'),
            'content' => $request->get('content'),
            'timestamp_publish' => $request->get('timestamp_publish')
        ]);
        $news->save();

        return redirect()->route('admin.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Request $request
     * @return Response
     */
    public function show(Request $request)
    {
        $title = $request->route('title');

        $one_news = News::where('title', $title)->firstOrFail();
        return view('admin.news.show', compact('one_news'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $news = News::find($id);
        return view('admin.news.edit', compact('news'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => [
                'required',
                'min:3',
                'max:128'
            ],
            'description' => 'required',
            'content' => 'required',
            'timestamp_publish' => 'required'
        ], [
            'timestamp_publish.required' => 'The date publish field is required.'
        ]);

        $news = News::find($id);
        $news->title = $request->get('title');
        $news->slug = Str::slug($news->title);
        $news->description = $request->get('description');
        $news->content = $request->get('content');
        $news->timestamp_publish = $request->get('timestamp_publish');

        $news->save();

        return redirect()->route('admin.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $news = News::find($id);
        $news->delete();

        return redirect()->route('admin.index');
    }
}

application/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

application/app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\News;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;

/**
 * Class NewsController
 * @package App\Http\Controllers
 */
class NewsController extends Controller
{
    /**
     * @return Factory|View
     */
    public function index()
    {
        $news = News::paginate(env('PAGINATE_COUNT_NEWS', 3));
        return view('news.index', compact('news'));
    }

    /**
     * @param Request $request
     * @return Factory|View
     */
    public function show(Request $request)
    {
        $slug = $request->route('slug');

        $one_news = News::where('slug', $slug)->firstOrFail();
        return view('news.show', compact('one_news'));
    }
}

application/resources/views/admin/news/edit.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        <h1>Edit news!</h1>
    </div>
    <hr class="w-100"/>
    <div class="col-12">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="form-errors">
                @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    </div>
    <div class="col-12">
        <form method="post" action="{{Illuminate\Support\Facades\URL::route('news.update', ['id' => $news->id])}}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="first_name">Title:</label>
                <input type="text" class="form-control" name="title" value="{{$news->title}}"/>
            </div>
            <div class="form-group">
                <label for="last_name">Description:</label>
                <textarea class="form-control" rows="5" name="description">{{$news->description}}</textarea>
            </div>
            <div class="form-group">
                <label for="last_name">Content:</label>
                <textarea class="form-control" rows="8" name="content">{{$news->content}}</textarea>
            </div>
            <div class="form-group">
                <label for="first_name">Date publish:</label>
                <input type="hidden" value="{{date('Y-m-d', strtotime($news->created_at))}}"/>
                <input type="date" class="form-control" name="timestamp_publish" value="{{date('Y-m-d', strtotime($news->timestamp_publish))}}"/>
            </div>
    </div>
    <hr class="w-100"/>
    <div class="col-12">
        <div class="row justify-content-between align-items-center">
            <div class="col-6">
                <a href="{{Illuminate\Support\Facades\URL::route('admin.index')}}"><< Back to list news</a>
            </div>
            <div class="col-6 text-right">
                <button type="submit" class="btn btn-success btn-sm">Update</button>
            </div>
        </div>
        </form>
    </div>
</div>
@endsection

application/resources/views/admin/news/form.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        <h1>Create news!</h1>
    </div>
    <hr class="w-100"/>
    <div class="col-12">
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul class="form-errors">
                @foreach ($errors->all() as $error)
                <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif
    </div>
    <div class="col-12">
        <form method="post" action="{{Illuminate\Support\Facades\URL::route('news.store')}}">
            @csrf
            <div class="form-group">
                <label for="first_name">Title:</label>
                <input type="text" class="form-control" name="title"/>
            </div>
            <div class="form-group">
                <label for="last_name">Description:</label>
                <textarea class="form-control" rows="5" name="description"></textarea>
            </div>
            <div class="form-group">
                <label for="last_name">Content:</label>
                <textarea class="form-control" rows="8" name="content"></textarea>
            </div>
            <div class="form-group">
                <label for="first_name">Date publish:</label>
                <input type="date" class="form-control" name="timestamp_publish"/>
            </div>
    </div>
    <hr class="w-100"/>
    <div class="col-12">
        <div class="row justify-content-between align-items-center">
            <div class="col-6">
                <a href="{{Illuminate\Support\Facades\URL::route('admin.index')}}"><< Back to list news</a>
            </div>
            <div class="col-6 text-right">
                <button type="submit" class="btn btn-success btn-sm">Create</button>
            </div>
        </div>
        </form>
    </div>
</div>
@endsection

application/resources/views/admin/news/index.blade.php
@php
/**
 * @var App\News $current_news
 */
@endphp

@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        <h1 class="text-center text-md-left">Admin list is news! <small><a href="{{Illuminate\Support\Facades\URL::route('admin.create')}}" class="btn btn-success btn-sm">Create news?!</a></small></h1>
    </div>
    <hr class="w-100"/>
    <div class="col-12 card-list">
        <div class="card-table">
            <div class="row card-header text-center">
                <div class="col-12 col-md-1"><strong>#ID</strong></div>
                <div class="col-12 col-md-6"><strong>Title/Description</strong></div>
                <div class="col-12 col-md-2"><strong>Date publish</strong></div>
                <div class="col-12 col-md-3"></div>
            </div>
            @foreach($news as $current_news)
            <div class="row card-body">
                <div class="col-12 col-md-1 text-center">{{$current_news->id}}</div>
                <div class="col-12 col-md-6">
                    <h5>{{$current_news->title}}</h5>
                    <br/>
                    <div>{{$current_news->description}}</div>
                </div>
                <div class="col-12 col-md-2 text-center">{{date('j F, Y', strtotime($current_news->timestamp_publish))}}</div>
                <div class="col-12 col-md-3">
                    <div class="row justify-content-center btn-group_kidys">
                        <a href="{{Illuminate\Support\Facades\URL::route('admin.edit', ['id' => $current_news->id])}}" class="btn btn-primary btn-sm">Edit</a>
                        <form method="post" action="{{Illuminate\Support\Facades\URL::route('admin.destroy', ['id' => $current_news->id])}}">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
    <hr class="w-100"/>
    <div class="col-12">
        {!! $news->links('vendor.pagination.simple-bootstrap-4') !!}
    </div>
</div>
@endsection

application/resources/views/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Laravel Project!</title>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>
<br/>
<div class="container">
    @yield('main')
</div>
<script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>
</html>

application/resources/views/index.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        <h1>Main page project! Select page bottom?!</h1>
    </div>
    <div class="col-12">
        <ul>
            <li><a href="{{Illuminate\Support\Facades\URL::route('news.all')}}">All news</a> (frontend)</li>
            <li><a href="{{Illuminate\Support\Facades\URL::route('admin.index')}}">Admin panel</a> (backend)</li>
        </ul>
    </div>
</div>
@endsection

application/resources/views/news/index.blade.php
@php
/**
 * @var App\News $current_news
 */
@endphp

@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        <h1>List all news!</h1>
    </div>
    <hr class="w-100"/>
    <div class="col-12 card-list">
        @foreach($news as $current_news)
            <div class="card card_kidys_theme">
                <h3 class="card-header">
                    <a href="{{Illuminate\Support\Facades\URL::route('news.one', ['slug' => $current_news->slug])}}">{{$current_news->title}}</a>
                </h3>
                <div class="card-body">
                    <div class="news-item__description">{{$current_news->description}}</div>
                </div>
                <div class="card-footer text-right">
                    <strong>created is:</strong>&nbsp;{{date('j F, Y', strtotime($current_news->timestamp_publish))}}
                </div>
            </div>
        @endforeach
    </div>
    <hr class="w-100"/>
    <div class="col-12">
        {!! $news->links('vendor.pagination.bootstrap-4') !!}
    </div>
</div>
@endsection

application/resources/views/news/show.blade.php
@extends('base')

@section('main')
<div class="row">
    <div class="col-12">
        <h1>Show one news!</h1>
    </div>
    <hr class="w-100"/>
    <div class="col-12">
        <div class="card">
            <h3 class="card-header">{{$one_news->title}}</h3>
            <div class="card-body">
                <div class="news-item__description">{{$one_news->description}}</div>
                <hr class="w-100"/>
                <div class="news-item__description">{{$one_news->content}}</div>
            </div>
            <div class="card-footer text-right">
                <strong>created is:</strong>&nbsp;{{date('j F, Y', strtotime($one_news->timestamp_publish))}}
            </div>
        </div>
    </div>
    <hr class="w-100"/>
    <div class="col-12">
        <a href="{{Illuminate\Support\Facades\URL::route('news.all')}}"><< Back to list news</a>
    </div>
</div>
@endsection